/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jeam
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        vt = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        kmr = new javax.swing.JMenu();
        fillkmr = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        viewkmr = new javax.swing.JMenuItem();
        vehicle = new javax.swing.JMenu();
        addvehicle = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        viewvehicles = new javax.swing.JMenuItem();
        driver = new javax.swing.JMenu();
        addriver = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu1.add(logout);

        jMenuBar1.add(jMenu1);

        vt.setText("Vehicleturnabout");
        vt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vtMouseClicked(evt);
            }
        });
        vt.add(jSeparator1);

        jMenuBar1.add(vt);

        kmr.setText("KM Overhaul");

        fillkmr.setText("Fill");
        fillkmr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fillkmrMouseClicked(evt);
            }
        });
        kmr.add(fillkmr);
        kmr.add(jSeparator2);

        viewkmr.setText("View");
        kmr.add(viewkmr);

        jMenuBar1.add(kmr);

        vehicle.setText("Vehicles");

        addvehicle.setText("Add");
        vehicle.add(addvehicle);
        vehicle.add(jSeparator3);

        viewvehicles.setText("View");
        vehicle.add(viewvehicles);

        jMenuBar1.add(vehicle);

        driver.setText("Drivers");

        addriver.setText("Add");
        addriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addriverMouseClicked(evt);
            }
        });
        driver.add(addriver);
        driver.add(jSeparator4);

        jMenuItem9.setText("View");
        driver.add(jMenuItem9);

        jMenuBar1.add(driver);

        jMenu2.setText("jMenu2");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void addriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addriverMouseClicked
        // TODO add your handling code here:
         drivers dr = new drivers();
                 dr.setVisible(true);
    }//GEN-LAST:event_addriverMouseClicked

    private void fillkmrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fillkmrMouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_fillkmrMouseClicked

    private void vtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vtMouseClicked
        // TODO add your handling code here:
        vehiclet vct = new vehiclet();
        vct.setVisible(true);
    }//GEN-LAST:event_vtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addriver;
    private javax.swing.JMenuItem addvehicle;
    private javax.swing.JMenu driver;
    private javax.swing.JMenuItem fillkmr;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu kmr;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenu vehicle;
    private javax.swing.JMenuItem viewkmr;
    private javax.swing.JMenuItem viewvehicles;
    private javax.swing.JMenu vt;
    // End of variables declaration//GEN-END:variables
}
